version: "3"
services:
  postgres:
    container_name: psql
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bravi
    ports:
      - "5433:5432"
    volumes:
      - db_postgres:/var/lib/postgresql/data
  node_api:
    container_name: api_bravi
    build:
      context: .
    depends_on:
      - postgres
    ports:
      - "3600:3600"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/bravi
    networks:
      - default
networks:
  default:
volumes:
  db_postgres:
